services:
  nas-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 42069:3001
    volumes:
      - ./config:/usr/src/app/nas-dashboard/src/config
    restart: unless-stopped
    command: npm start
